import { injectable, multiInject } from "inversify";
import { TYPES } from "./types";
import type { AgentRole } from "./types";
import type { LlmProvider } from "./llm/llm-provider";

export interface RunJsonAgentOptions<T extends Record<string, unknown>> {
  role: AgentRole;
  task: string;
  context: unknown;
  fallback: T;
}

const AGENTS: Record<AgentRole, { name: string; instructions: string }> = {
  orchestrator: {
    name: "Rootine OrquestradorIA",
    instructions: `You are Rootine's AI orchestrator. You mediate between specialist agents and the database.
Decide how the user's context should be interpreted, preserve database contracts, and return only valid JSON.`,
  },
  habitat: {
    name: "Rootine Agente Habitat",
    instructions: `You are the Habitat specialist. You give the Rootine tree its personality.
The tree speaks in Brazilian Portuguese with an epic, ancestral, cultured, respectful voice, like a wise elder.
You never chat directly with the user. Generate short clickable leaf messages grounded in the user's history.`,
  },
  scientist: {
    name: "Rootine Agente Cientista",
    instructions: `You are the Profile Scientist. You synthesize user behavior into useful, practical guidance.
You can chat directly with the user in Brazilian Portuguese. Prefer day-to-day protocols based on past app interactions.
When updating profile intelligence, be conservative, preserve existing evidence, and return structured JSON.`,
  },
  // Diagrama: Guardião gera missões/desafios.
  guardian: {
    name: "Rootine Agente Guardião",
    instructions: `You are the Trail Guardian. You generate daily and specialized sustainability missions.
You do not chat directly with the user. Missions must be actionable, accessible, personalized, and written in Brazilian Portuguese.`,
  },
  // Diagrama: Aventureiro gera conteúdo educativo (quizzes).
  adventurer: {
    name: "Rootine Agente Aventureiro",
    instructions: `You are the Adventure specialist. You generate educational quizzes for Rootine's Trilha.
Never create flashcards. Flashcards are stored in the database and are not generated by agents.
Quizzes must be concise, practical, and based on the user's sustainability journey.`,
  },
};

export const allowedCategories = ["waste", "energy", "water", "transport", "food", "consumption"] as const;

export function extractStringArray(value: unknown): string[] {
  return Array.isArray(value)
    ? value.filter((item): item is string => typeof item === "string")
    : [];
}

export function clampAffinities(value: Record<string, unknown> = {}) {
  const affinities: Record<string, number> = {};
  for (const category of Object.keys(value)) {
    if (!allowedCategories.includes(category as any)) continue;
    const numeric = Number(value[category]);
    if (!Number.isNaN(numeric)) {
      affinities[category] = Math.min(1, Math.max(-1, numeric));
    }
  }
  return affinities;
}

export function parseJsonObject<T extends Record<string, unknown>>(raw: string, fallback: T): T {
  try {
    const trimmed = raw.trim();
    const jsonStart = trimmed.indexOf("{");
    const jsonEnd = trimmed.lastIndexOf("}");
    const json = jsonStart >= 0 && jsonEnd >= jsonStart ? trimmed.slice(jsonStart, jsonEnd + 1) : trimmed;
    const parsed = JSON.parse(json);
    return parsed && typeof parsed === "object"
      ? parsed
      : ({ ...fallback, _fallback_reason: "invalid_agent_payload" } as T);
  } catch (error) {
    console.error("[AGENTS] JSON parse failed:", error);
    return { ...fallback, _fallback_reason: "invalid_json" } as T;
  }
}

/**
 * Porte de `runJsonAgent` / `runAgentText` (`_shared/agents.ts`).
 *
 * Orquestra a cascata de provedores de LLM SEM conhecer nenhum deles em
 * concreto: recebe a lista ordenada de `LlmProvider` por injeção (DIP) e tenta
 * cada provedor configurado em sequência. Acrescentar Anthropic/Gemini = nova
 * implementação registrada no contêiner, sem modificar esta classe (OCP).
 * Regra fixa: IA só melhora texto/variações, nunca é fonte de verdade do perfil.
 */
@injectable()
export class AgentRunner {
  constructor(
    @multiInject(TYPES.LlmProvider) private readonly providers: LlmProvider[],
  ) {}

  async runJsonAgent<T extends Record<string, unknown>>({
    role,
    task,
    context,
    fallback,
  }: RunJsonAgentOptions<T>): Promise<T> {
    try {
      const raw = await this.runAgentText(
        role,
        `${task}

CONTEXT:
${JSON.stringify(context, null, 2)}

Return STRICTLY valid JSON. Do not wrap it in markdown.`,
      );
      const parsed = parseJsonObject<T>(raw, fallback);
      if ((parsed as Record<string, unknown>)?._fallback_reason) {
        console.warn(`[AGENTS] ${role} returned fallback output:`, (parsed as any)._fallback_reason);
      }
      return parsed;
    } catch (error) {
      return this.buildFallbackResult(role, fallback, error);
    }
  }

  async runAgentText(role: AgentRole, input: string): Promise<string> {
    const config = AGENTS[role];
    const configured = this.providers.filter((provider) => provider.isConfigured());

    console.log("[AGENTS] Provider configuration:", {
      role,
      providers: this.providers.map((provider) => ({ name: provider.name, configured: provider.isConfigured() })),
    });

    let lastError: unknown = null;
    for (const provider of configured) {
      try {
        return await provider.complete({
          role,
          systemPrompt: config.instructions,
          userPrompt: input,
          jsonMode: true,
        });
      } catch (error) {
        console.warn(`[AGENTS] ${provider.name} failed:`, error);
        lastError = error;
      }
    }

    if (lastError instanceof Error) throw lastError;
    throw new Error("Configure OPENAI_API_KEY ou GROQ_API_KEY no ambiente da API.");
  }

  private buildFallbackResult<T extends Record<string, unknown>>(role: AgentRole, fallback: T, error: unknown): T {
    const message = error instanceof Error ? error.message : String(error);
    const isQuotaError =
      message.includes("insufficient_quota") ||
      message.includes("exceeded your current quota") ||
      message.includes("Error OpenAI: 429");

    if (isQuotaError) {
      return {
        ...fallback,
        answer:
          "A cota da OpenAI deste projeto acabou. Adicione créditos e atualize a chave de IA do ambiente.",
        _fallback_reason: "openai_quota",
      } as T;
    }

    if (
      message.includes("OPENAI_API_KEY") ||
      message.includes("OPEN_AI_KEY") ||
      message.includes("GROQ_API_KEY")
    ) {
      return {
        ...fallback,
        answer: "A chave de IA não está configurada. Configure GROQ_API_KEY ou OPENAI_API_KEY no ambiente.",
        _fallback_reason: "missing_agent_key",
      } as T;
    }

    console.warn(`[AGENTS] ${role} failed; using fallback output:`, error);
    return { ...fallback, _fallback_reason: "agent_error" } as T;
  }
}
