import type { MissionValidationOptions } from "./validation";

export interface MissionCandidateFixture {
  name: string;
  expectedValid: boolean;
  caseTags: string[];
  candidate: unknown;
  options?: MissionValidationOptions;
}

export interface BadAiResponseFixture {
  name: string;
  response: unknown;
  expectedErrors: string[];
}

export interface FeedbackFixture {
  name: string;
  expectedValid: boolean;
  classification: unknown;
}

export const PROMPT3_PROFILE_FACTS = [
  {
    fact_key: "constraint.time.low",
    fact_type: "constraint",
    category: "consumption",
    value: { minutes_available: 5 },
    confidence: 0.85,
    active: true,
  },
  {
    fact_key: "constraint.money.low",
    fact_type: "constraint",
    category: "consumption",
    value: { cost_level_max: "free" },
    confidence: 0.9,
    active: true,
  },
  {
    fact_key: "water.needs_longer_shower_for_medication",
    fact_type: "constraint",
    category: "water",
    value: { safety_note: "Do not change medical step." },
    confidence: 0.95,
    active: true,
  },
  {
    fact_key: "capability.has_kitchen_access",
    fact_type: "capability",
    category: "food",
    value: true,
    confidence: 0.8,
    active: true,
  },
  {
    fact_key: "habit.uses_public_transport",
    fact_type: "habit",
    category: "transport",
    value: true,
    confidence: 0.75,
    active: true,
  },
  {
    fact_key: "deficit.recycling_inconsistent",
    fact_type: "deficit",
    category: "waste",
    value: true,
    confidence: 0.7,
    active: true,
  },
  {
    fact_key: "preference.small_changes",
    fact_type: "preference",
    category: "consumption",
    value: true,
    confidence: 0.8,
    active: true,
  },
] satisfies MissionValidationOptions["facts"];

const baseImpact = {
  water_l: { low: 0, mid: 0, high: 0, confidence: 0.2 },
  co2_kg: { low: 0, mid: 0, high: 0, confidence: 0.2 },
  waste_g: { low: 0, mid: 0, high: 0, confidence: 0.2 },
  energy_kwh: { low: 0, mid: 0, high: 0, confidence: 0.2 },
};

export const missionCandidateFixtures: MissionCandidateFixture[] = [
  {
    name: "valid_medication_shower_pause",
    expectedValid: true,
    caseTags: ["banho com medicamento", "water", "safety"],
    options: { facts: PROMPT3_PROFILE_FACTS },
    candidate: {
      title: "Pausa segura no banho",
      description: "Hoje, desligue o chuveiro por ate 1 minuto apenas na etapa em que a agua corrente nao interfere no cuidado medico.",
      category: "water",
      environmental_goal: "reduce_water_use",
      difficulty: 1,
      effort_minutes: 2,
      cost_level: "free",
      used_fact_keys: ["water.needs_longer_shower_for_medication", "constraint.time.low"],
      personalization_reason: "Respeita a etapa medica e reduz agua apenas onde e seguro para a rotina informada.",
      expected_impact: { ...baseImpact, water_l: { low: 3, mid: 6, high: 10, confidence: 0.45 } },
      pattern_key: "water.pause_running_shower_when_safe",
      xp_reward: 10,
    },
  },
  {
    name: "valid_low_money_reuse_container",
    expectedValid: true,
    caseTags: ["pouco dinheiro", "consumption"],
    options: { facts: PROMPT3_PROFILE_FACTS },
    candidate: {
      title: "Reuso antes de comprar",
      description: "Antes de comprar um organizador, separe um pote ou embalagem limpa que voce ja tem e use por uma semana.",
      category: "consumption",
      environmental_goal: "reuse_existing_item_to_reduce_consumption",
      difficulty: 1,
      effort_minutes: 5,
      cost_level: "free",
      used_fact_keys: ["constraint.money.low"],
      personalization_reason: "Evita gasto novo e usa algo que ja existe, respeitando a friccao financeira registrada.",
      expected_impact: { ...baseImpact, waste_g: { low: 20, mid: 60, high: 120, confidence: 0.35 } },
      pattern_key: "consumption.reuse_container_before_buying",
      xp_reward: 10,
    },
  },
  {
    name: "valid_low_time_switch_check",
    expectedValid: true,
    caseTags: ["pouco tempo", "energy"],
    options: { facts: PROMPT3_PROFILE_FACTS },
    candidate: {
      title: "Cheque rapido de stand-by",
      description: "Escolha um aparelho que nao precisa ficar em stand-by hoje e desligue da tomada ao sair.",
      category: "energy",
      environmental_goal: "reduce_standby_energy_use",
      difficulty: 1,
      effort_minutes: 2,
      cost_level: "free",
      used_fact_keys: ["constraint.time.low"],
      personalization_reason: "Cabe em poucos minutos e reduz consumo eletrico sem exigir compra ou mudanca longa.",
      expected_impact: { ...baseImpact, energy_kwh: { low: 0.01, mid: 0.04, high: 0.1, confidence: 0.35 } },
      pattern_key: "energy.turn_off_standby_one_device",
      xp_reward: 10,
    },
  },
  {
    name: "valid_transport_route_review",
    expectedValid: true,
    caseTags: ["transport"],
    options: { facts: PROMPT3_PROFILE_FACTS },
    candidate: {
      title: "Rota curta sem carro",
      description: "Para um deslocamento curto desta semana, compare se caminhar ou usar transporte publico resolve sem aumentar seu tempo de forma insegura.",
      category: "transport",
      environmental_goal: "reduce_short_trip_car_emissions",
      difficulty: 2,
      effort_minutes: 10,
      cost_level: "free",
      used_fact_keys: ["habit.uses_public_transport"],
      personalization_reason: "Aproveita o habito de transporte publico e limita a mudanca a um trajeto curto e seguro.",
      expected_impact: { ...baseImpact, co2_kg: { low: 0.2, mid: 0.7, high: 1.5, confidence: 0.4 } },
      pattern_key: "transport.replace_one_short_car_trip",
      xp_reward: 16,
    },
  },
  {
    name: "valid_recycling_single_material",
    expectedValid: true,
    caseTags: ["waste"],
    options: { facts: PROMPT3_PROFILE_FACTS },
    candidate: {
      title: "Um material bem separado",
      description: "Hoje, escolha apenas plastico ou papel limpo e deixe separado do lixo comum para facilitar o descarte correto.",
      category: "waste",
      environmental_goal: "separate_recyclable_material_to_reduce_waste",
      difficulty: 1,
      effort_minutes: 4,
      cost_level: "free",
      used_fact_keys: ["deficit.recycling_inconsistent"],
      personalization_reason: "Foca em um unico material para reduzir atrito onde a separacao ainda e inconsistente.",
      expected_impact: { ...baseImpact, waste_g: { low: 50, mid: 150, high: 300, confidence: 0.45 } },
      pattern_key: "waste.separate_one_clean_material",
      xp_reward: 10,
    },
  },
  {
    name: "valid_food_leftover_plan",
    expectedValid: true,
    caseTags: ["food"],
    options: { facts: PROMPT3_PROFILE_FACTS },
    candidate: {
      title: "Plano de sobra visivel",
      description: "Coloque uma sobra comestivel em recipiente visivel na geladeira e defina em qual refeicao ela sera usada.",
      category: "food",
      environmental_goal: "reduce_food_waste",
      difficulty: 2,
      effort_minutes: 7,
      cost_level: "free",
      used_fact_keys: ["capability.has_kitchen_access"],
      personalization_reason: "Usa o acesso a cozinha para reduzir desperdicio de alimento sem pedir compra nova.",
      expected_impact: { ...baseImpact, waste_g: { low: 80, mid: 250, high: 500, confidence: 0.5 } },
      pattern_key: "food.plan_one_leftover_meal",
      xp_reward: 16,
    },
  },
  {
    name: "valid_cold_start_fact",
    expectedValid: true,
    caseTags: ["cold_start"],
    candidate: {
      title: "Primeiro ponto de observacao",
      description: "Observe por 3 minutos onde aparece mais descarte na sua rotina de hoje e registre apenas um ajuste possivel.",
      category: "waste",
      environmental_goal: "identify_waste_reduction_opportunity",
      difficulty: 1,
      effort_minutes: 3,
      cost_level: "free",
      used_fact_keys: ["cold_start.onboarding_completed"],
      personalization_reason: "Como ainda ha poucos fatos, usa um fato explicito de inicio para observar sem impor custo.",
      expected_impact: { ...baseImpact, waste_g: { low: 1, mid: 5, high: 20, confidence: 0.2 } },
      pattern_key: "waste.observe_one_discard_point",
      xp_reward: 10,
    },
  },
  {
    name: "valid_medium_experienced_user",
    expectedValid: true,
    caseTags: ["experienced"],
    options: { facts: PROMPT3_PROFILE_FACTS, userLevel: 8 },
    candidate: {
      title: "Mapa de tres vazamentos de consumo",
      description: "Liste tres compras recorrentes do mes e marque uma que pode ser adiada, reparada ou substituida por reuso.",
      category: "consumption",
      environmental_goal: "reduce_recurring_unnecessary_consumption",
      difficulty: 3,
      effort_minutes: 20,
      cost_level: "free",
      used_fact_keys: ["preference.small_changes", "constraint.money.low"],
      personalization_reason: "Para um usuario experiente, aprofunda a analise sem exigir gasto e preserva mudancas pequenas.",
      expected_impact: { ...baseImpact, waste_g: { low: 100, mid: 400, high: 1200, confidence: 0.35 } },
      pattern_key: "consumption.audit_recurring_purchases",
      xp_reward: 25,
    },
  },
  {
    name: "valid_energy_natural_light",
    expectedValid: true,
    caseTags: ["energy"],
    options: { facts: PROMPT3_PROFILE_FACTS },
    candidate: {
      title: "Janela antes da lampada",
      description: "Em um periodo claro do dia, use luz natural por 20 minutos antes de acender uma lampada sem prejudicar seguranca ou conforto.",
      category: "energy",
      environmental_goal: "reduce_lighting_energy_use",
      difficulty: 1,
      effort_minutes: 1,
      cost_level: "free",
      used_fact_keys: ["preference.small_changes"],
      personalization_reason: "Aproveita a preferencia por pequenas mudancas e reduz energia sem custo.",
      expected_impact: { ...baseImpact, energy_kwh: { low: 0.01, mid: 0.03, high: 0.08, confidence: 0.3 } },
      pattern_key: "energy.use_daylight_once",
      xp_reward: 10,
    },
  },
  {
    name: "valid_water_leak_check",
    expectedValid: true,
    caseTags: ["water"],
    options: { facts: PROMPT3_PROFILE_FACTS },
    candidate: {
      title: "Escuta de vazamento",
      description: "Antes de dormir, confira por 2 minutos se alguma torneira ficou pingando e feche apenas o que estiver sob seu controle.",
      category: "water",
      environmental_goal: "reduce_water_leak_waste",
      difficulty: 1,
      effort_minutes: 2,
      cost_level: "free",
      used_fact_keys: ["constraint.time.low"],
      personalization_reason: "Respeita o pouco tempo disponivel e atua somente onde ha controle direto.",
      expected_impact: { ...baseImpact, water_l: { low: 1, mid: 4, high: 15, confidence: 0.35 } },
      pattern_key: "water.check_one_leak",
      xp_reward: 10,
    },
  },
  {
    name: "invalid_experienced_trivial_lights",
    expectedValid: false,
    caseTags: ["usuario experiente recebendo missao trivial"],
    options: { facts: PROMPT3_PROFILE_FACTS, userLevel: 8 },
    candidate: {
      title: "Desligue a luz",
      description: "Desligue uma luz por 1 minuto ao sair do comodo.",
      category: "energy",
      environmental_goal: "reduce_lighting_energy_use",
      difficulty: 1,
      effort_minutes: 1,
      cost_level: "free",
      used_fact_keys: ["preference.small_changes"],
      personalization_reason: "Usuario experiente precisa de algo simples e rapido.",
      expected_impact: { ...baseImpact, energy_kwh: { low: 0.001, mid: 0.002, high: 0.004, confidence: 0.2 } },
      pattern_key: "energy.turn_off_light",
    },
  },
  {
    name: "invalid_increases_consumption",
    expectedValid: false,
    caseTags: ["missao que aumenta consumo"],
    candidate: {
      title: "Compre garrafas novas",
      description: "Compre mais garrafas descartaveis para lembrar de beber agua durante o dia.",
      category: "consumption",
      environmental_goal: "reduce_waste",
      difficulty: 1,
      effort_minutes: 10,
      cost_level: "medium",
      used_fact_keys: ["preference.small_changes"],
      personalization_reason: "Aumenta compras para facilitar um habito, mas sem justificativa ambiental direta.",
      expected_impact: { ...baseImpact, waste_g: { low: 10, mid: 50, high: 100, confidence: 0.2 } },
    },
  },
  {
    name: "invalid_missing_used_fact_keys",
    expectedValid: false,
    caseTags: ["IA omitindo used_fact_keys"],
    candidate: {
      title: "Separe reciclaveis",
      description: "Separe os reciclaveis limpos de hoje para reduzir residuos misturados.",
      category: "waste",
      environmental_goal: "separate_recyclables_to_reduce_waste",
      difficulty: 1,
      effort_minutes: 5,
      cost_level: "free",
      used_fact_keys: [],
      personalization_reason: "A missao foi criada sem conectar fatos reais do usuario.",
      expected_impact: { ...baseImpact, waste_g: { low: 30, mid: 100, high: 200, confidence: 0.4 } },
    },
  },
  {
    name: "invalid_invented_category",
    expectedValid: false,
    caseTags: ["IA inventando categoria"],
    candidate: {
      title: "Cuide da varanda",
      description: "Organize plantas da varanda para melhorar sua relacao com o espaco.",
      category: "garden",
      environmental_goal: "reduce_waste",
      difficulty: 1,
      effort_minutes: 10,
      cost_level: "free",
      used_fact_keys: ["preference.small_changes"],
      personalization_reason: "Usa uma categoria inventada que nao pertence ao contrato do Rootine.",
      expected_impact: { ...baseImpact, waste_g: { low: 1, mid: 3, high: 5, confidence: 0.2 } },
    },
  },
  {
    name: "invalid_mixed_structured_language",
    expectedValid: false,
    caseTags: ["IA misturando idioma nos campos estruturados"],
    candidate: {
      title: "Economia de agua",
      description: "Feche a torneira por alguns minutos para reduzir desperdicio.",
      category: "agua",
      environmental_goal: "reduzir agua",
      difficulty: "easy",
      effort_minutes: 5,
      cost_level: "gratis",
      used_fact_keys: ["constraint.time.low"],
      personalization_reason: "Campos estruturados devem seguir o contrato em ingles controlado.",
      expected_impact: { ...baseImpact, water_l: { low: 1, mid: 3, high: 5, confidence: 0.3 } },
    },
  },
  {
    name: "invalid_generic_fallback",
    expectedValid: false,
    caseTags: ["fallback generico de missao"],
    candidate: {
      title: "Missao da Pequena Mudanca",
      description: "Escolha uma acao simples e sustentavel para praticar hoje por pelo menos 10 minutos.",
      category: "consumption",
      environmental_goal: "reduce_consumption",
      difficulty: 1,
      effort_minutes: 10,
      cost_level: "free",
      used_fact_keys: ["cold_start.onboarding_completed"],
      personalization_reason: "Criei uma missao acessivel porque os dados disponiveis ainda nao foram suficientes para uma personalizacao mais precisa.",
      expected_impact: { ...baseImpact, waste_g: { low: 1, mid: 2, high: 5, confidence: 0.2 } },
    },
  },
  {
    name: "invalid_missing_environmental_goal",
    expectedValid: false,
    caseTags: ["missao sem environmental_goal"],
    candidate: {
      title: "Observe sua rotina",
      description: "Observe sua rotina por alguns minutos e anote uma coisa que chamou atencao.",
      category: "consumption",
      environmental_goal: "",
      difficulty: 1,
      effort_minutes: 5,
      cost_level: "free",
      used_fact_keys: ["preference.small_changes"],
      personalization_reason: "Usa a preferencia por mudancas pequenas, mas nao define objetivo ambiental.",
      expected_impact: { ...baseImpact, waste_g: { low: 1, mid: 2, high: 4, confidence: 0.2 } },
    },
  },
  {
    name: "invalid_zero_impact",
    expectedValid: false,
    caseTags: ["impacto zerado"],
    candidate: {
      title: "Organize a mesa",
      description: "Organize sua mesa por 10 minutos para se sentir melhor com a rotina.",
      category: "consumption",
      environmental_goal: "reduce_unnecessary_consumption",
      difficulty: 1,
      effort_minutes: 10,
      cost_level: "free",
      used_fact_keys: ["preference.small_changes"],
      personalization_reason: "A missao parece confortavel, mas nao registra impacto ambiental positivo.",
      expected_impact: baseImpact,
    },
  },
  {
    name: "invalid_unknown_fact",
    expectedValid: false,
    caseTags: ["fato inexistente"],
    options: { facts: PROMPT3_PROFILE_FACTS },
    candidate: {
      title: "Troca de transporte",
      description: "Troque um trajeto longo por bicicleta sem verificar seguranca ou disponibilidade.",
      category: "transport",
      environmental_goal: "reduce_transport_emissions",
      difficulty: 2,
      effort_minutes: 20,
      cost_level: "free",
      used_fact_keys: ["transport.has_bike"],
      personalization_reason: "Usa um fato que nao existe no perfil ativo e pode inventar capacidade.",
      expected_impact: { ...baseImpact, co2_kg: { low: 0.2, mid: 1, high: 2, confidence: 0.3 } },
    },
  },
  {
    name: "invalid_repeated_pattern",
    expectedValid: false,
    caseTags: ["repeticao"],
    options: { facts: PROMPT3_PROFILE_FACTS, recentPatternKeys: ["energy.turn_off_standby_one_device"] },
    candidate: {
      title: "Cheque rapido de stand-by",
      description: "Desligue um aparelho em stand-by hoje para economizar energia.",
      category: "energy",
      environmental_goal: "reduce_standby_energy_use",
      difficulty: 1,
      effort_minutes: 2,
      cost_level: "free",
      used_fact_keys: ["constraint.time.low"],
      personalization_reason: "Cabe no tempo disponivel, mas repete exatamente o pattern recente.",
      expected_impact: { ...baseImpact, energy_kwh: { low: 0.01, mid: 0.04, high: 0.1, confidence: 0.35 } },
      pattern_key: "energy.turn_off_standby_one_device",
    },
  },
];

export const badAiResponseFixtures: BadAiResponseFixture[] = [
  {
    name: "plain_text_not_json",
    response: "Claro! Desligue as luzes e seja sustentavel.",
    expectedErrors: ["mission_candidate_required"],
  },
  {
    name: "missing_environmental_goal",
    response: { title: "Observe", description: "Observe sua rotina por 10 minutos." },
    expectedErrors: ["environmental_goal_required"],
  },
  {
    name: "invalid_category",
    response: { category: "natureza" },
    expectedErrors: ["category_invalid"],
  },
  {
    name: "empty_used_fact_keys",
    response: { used_fact_keys: [] },
    expectedErrors: ["used_fact_keys_required"],
  },
  {
    name: "generic_fallback_title",
    response: {
      title: "Missao da Pequena Mudanca",
      description: "Escolha uma acao simples e sustentavel para praticar hoje por pelo menos 10 minutos.",
      category: "consumption",
      environmental_goal: "reduce_consumption",
      difficulty: 1,
      effort_minutes: 10,
      cost_level: "free",
      used_fact_keys: ["cold_start.onboarding_completed"],
      personalization_reason: "Criei uma missao acessivel porque os dados disponiveis ainda nao foram suficientes para uma personalizacao mais precisa.",
      expected_impact: { ...baseImpact, waste_g: { low: 1, mid: 2, high: 4, confidence: 0.2 } },
    },
    expectedErrors: ["generic_fallback_mission"],
  },
  {
    name: "bad_impact_order",
    response: { expected_impact: { water_l: { low: 10, mid: 5, high: 1, confidence: 0.5 } } },
    expectedErrors: ["impact_range_order:water_l"],
  },
  {
    name: "confidence_out_of_range",
    response: { expected_impact: { co2_kg: { low: 0, mid: 1, high: 2, confidence: 2 } } },
    expectedErrors: ["impact_confidence_out_of_range:co2_kg"],
  },
  {
    name: "cost_level_portuguese",
    response: { cost_level: "gratis" },
    expectedErrors: ["cost_level_invalid"],
  },
  {
    name: "difficulty_text",
    response: { difficulty: "facil" },
    expectedErrors: ["difficulty_invalid"],
  },
  {
    name: "increased_consumption",
    response: {
      title: "Compre mais embalagens",
      description: "Compre mais potes novos para organizar tudo.",
      personalization_reason: "Ajuda a organizar.",
    },
    expectedErrors: ["mission_increases_consumption_without_justification"],
  },
];

export const feedbackFixtures: FeedbackFixture[] = [
  {
    name: "valid_low_time_constraint",
    expectedValid: true,
    classification: {
      kind: "constraint",
      summary: "Usuario relata pouco tempo durante dias uteis.",
      severity: "medium",
      category: "consumption",
      fact_key: "constraint.time.low",
    },
  },
  {
    name: "valid_hard_block_health",
    expectedValid: true,
    classification: {
      kind: "hard_block",
      summary: "Usuario nao pode alterar a etapa medica do banho.",
      severity: "high",
      category: "water",
      fact_key: "water.needs_longer_shower_for_medication",
      creates_hard_block: true,
    },
  },
  {
    name: "valid_preference_small_steps",
    expectedValid: true,
    classification: {
      kind: "preference",
      summary: "Usuario prefere mudancas pequenas e rapidas.",
      severity: "low",
      category: "consumption",
    },
  },
  {
    name: "valid_deficit_recycling",
    expectedValid: true,
    classification: {
      kind: "deficit",
      summary: "Usuario ainda mistura reciclaveis com lixo comum.",
      severity: "medium",
      category: "waste",
    },
  },
  {
    name: "valid_mission_adjustment",
    expectedValid: true,
    classification: {
      kind: "mission_adjustment",
      summary: "Usuario pede missao que caiba antes do trabalho.",
      severity: "low",
      category: "energy",
    },
  },
  {
    name: "valid_unclear",
    expectedValid: true,
    classification: {
      kind: "unclear",
      summary: "Feedback ambiguo e insuficiente para criar fato.",
      severity: "low",
    },
  },
  {
    name: "invalid_constraint_without_fact_key",
    expectedValid: false,
    classification: {
      kind: "constraint",
      summary: "Usuario relata uma restricao duravel.",
      severity: "medium",
      category: "transport",
    },
  },
  {
    name: "invalid_category",
    expectedValid: false,
    classification: {
      kind: "preference",
      summary: "Usuario prefere acoes em jardim.",
      severity: "low",
      category: "garden",
    },
  },
];
